# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ckk3nuBx3g2p9w1zr5CmIM-w2SE6bKHr
"""

import pandas as pd
salary = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Salary%20Data.csv')
salary.head(10)
salary.info()
salary.describe()

salary.columns

y=salary['Salary']
x=salary[['Experience Years']]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=2529)

from sklearn.linear_model import LinearRegression
model=LinearRegression()

model.fit(x_train,y_train)

model.intercept_

model.coef_

y_pred = model.predict(x_test)

from sklearn.metrics import mean_absolute_percentage_error

mean_absolute_percentage_error(y_test,y_pred)